# Generated by Django 4.2.3 on 2023-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVibesU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(default='album', max_length=250),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(default='artist', max_length=250),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.CharField(default='podcast', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(default='image', max_length=250),
        ),
    ]
