# Generated by Django 4.2.3 on 2023-08-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVibesU', '0002_album_image_artist_image_podcast_image_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
