# Generated by Django 4.2.3 on 2023-08-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVibesU', '0003_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
