# Generated by Django 4.2.3 on 2023-08-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVibesU', '0007_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mp3_track',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
