# Generated by Django 4.2.3 on 2023-09-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVibesU', '0009_rename_image_artist_link_address_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='link_address_image',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='image',
            new_name='link_address_image',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='image',
            new_name='link_address_image',
        ),
    ]
