# Generated by Django 4.2.3 on 2023-09-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVibesU', '0010_rename_image_album_link_address_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='mp3_track',
            new_name='link_address_mp3_track',
        ),
    ]
